# Generated by Django 4.1.2 on 2022-10-10 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='person',
        ),
        migrations.AddField(
            model_name='mark',
            name='riddle',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='riddles.riddle', verbose_name='Загадка'),
            preserve_default=False,
        ),
    ]
